name: recipe_task_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Network Service
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # A library that checks for internet by opening a socket to a list of specified addresses
  internet_connection_checker: ^1.0.0+1
  
  # JSON
  json_annotation: ^4.9.0

  # Images Utils
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0

  # Dependency Injection
  get_it: ^8.2.0

  # UI Components
  equatable: ^2.0.5
  skeletonizer: ^1.4.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Black.otf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
